---
# tasks file for dovecot
- name: load default variables
  include_vars:
    file: default.yml

- name: load os-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - default.yml

- name: install software
  package:
    name: "{{ item }}"
  with_items:
    - "{{ dovecot_packages }}"
  notify:
    - copy sample configuration

- name: flush handlers
  meta: flush_handlers

- name: configure software
  lineinfile:
    path: /etc/dovecot/conf.d/10-mail.conf
    regexp: "^mail_location"
    line: "mail_location = {{ dovecot_mailbox_location }}"

- name: start and enable software
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items: "{{ dovecot_service }}"
  when:
    - ansible_virtualization_type != "docker"
