---
# tasks file for dovecot
- name: install dovecot
  package:
    name: "{{ dovecot_packages[ansible_distribution]
          | default(dovecot_packages['default']) }}"
    state: "{{ dovecot_package_state }}"
  notify:
    - copy sample configuration

- name: flush handlers
  meta: flush_handlers

- name: configure dovecot
  lineinfile:
    path: /etc/dovecot/conf.d/10-mail.conf
    regexp: "^mail_location"
    line: "mail_location = {{ dovecot_mailbox_location }}"

- name: start and enable dovecot
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items: "{{ dovecot_service }}"
  when:
    - ansible_virtualization_type != "docker"
