---
# tasks file for dovecot
- name: include assert.yml
  include_tasks: assert.yml

- name: install dovecot
  package:
    name: "{{ dovecot_packages }}"
    state: present
  notify:
    - copy sample configuration

- name: flush handlers
  meta: flush_handlers

- name: configure mail_location
  lineinfile:
    path: /etc/dovecot/conf.d/10-mail.conf
    regexp: "^mail_location"
    line: "mail_location = {{ dovecot_mailbox_location }}"

- name: configure mail_access_groups
  lineinfile:
    path: /etc/dovecot/conf.d/10-mail.conf
    regexp: "^mail_access_groups"
    line: "mail_access_groups = {{ dovecot_mail_access_groups }}"

- name: start and enable dovecot
  service:
    name: "{{ dovecot_service }}"
    state: started
    enabled: yes
