---
# tasks file for dovecot
- name: install software
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ dovecot_packages[ansible_distribution ~ '-' ~ ansible_distribution_major_version]
      | default(dovecot_packages[ansible_distribution]
      | default(dovecot_packages['default'] )) }}"

- name: configure software
  lineinfile:
    path: /etc/dovecot/conf.d/10-mail.conf
    regexp: "^mail_location"
    line: "mail_location = {{ dovecot_mailbox_location }}"

- name: start and enable software
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - "{{ dovecot_services[ansible_distribution ~ '-' ~ ansible_distribution_major_version]
      | default(dovecot_services[ansible_distribution]
      | default(dovecot_services['default'] )) }}"
  when:
    - ansible_virtualization_type != "docker"
