---
# tasks file for dovecot
- name: install dovecot
  package:
    name: "{{ dovecot_packages }}"
    state: "{{ dovecot_package_state }}"
  notify:
    - copy sample configuration
  register: dovecot_install_dovecot
  until: dovecot_install_dovecot is succeeded
  retries: 3

- name: flush handlers
  meta: flush_handlers

- name: configure dovecot
  lineinfile:
    path: /etc/dovecot/conf.d/10-mail.conf
    regexp: "^mail_location"
    line: "mail_location = {{ dovecot_mailbox_location }}"

- name: place selinux type enforcement
  copy:
    src: my-dovecot.te
    dest: /etc/my-dovecot.te
  when:
    - ansible_selinux is defined
    - ansible_selinux
    - ansible_selinux.status == "enabled"
  notify:
    - create dovecot selinux mod
    - create dovecot selinux pp
    - load dovecot selinux pp

- name: start and enable dovecot
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items: "{{ dovecot_service }}"
  when:
    - ansible_virtualization_type != "docker" or dovecot_ignore_docker
